//! Pest parser infrastructure for bundlebase custom SQL grammar.
//!
//! This module provides:
//! - The `BundlebaseParser` struct generated by pest
//! - Helper functions for parsing common elements (strings, identifiers, etc.)
//! - Error formatting utilities

use crate::bundle::pack::JoinTypeOption;
use crate::BundlebaseError;
use pest_derive::Parser;

/// Pest parser for bundlebase custom SQL grammar.
///
/// This parser handles bundlebase-specific syntax like FILTER, ATTACH, JOIN, etc.
/// Standard SQL is handled by sqlparser-rs.
#[derive(Parser)]
#[grammar = "bundle/command/parser/grammar.pest"]
pub struct BundlebaseParser;

/// Format a pest error into a user-friendly BundlebaseError.
pub fn format_pest_error(error: pest::error::Error<Rule>, sql: &str) -> BundlebaseError {
    let (line, col) = match &error.line_col {
        pest::error::LineColLocation::Pos((l, c)) => (*l, *c),
        pest::error::LineColLocation::Span((l, c), _) => (*l, *c),
    };

    format!(
        "Syntax error at line {}, column {}:\n{}\n\nSQL:\n{}",
        line, col, error, sql
    )
    .into()
}

/// Extract string content from a quoted string, handling escape sequences.
///
/// Supports both single-quoted ('...') and double-quoted ("...") strings.
pub fn extract_string_content(quoted: &str) -> Result<String, BundlebaseError> {
    let trimmed = quoted.trim();

    // Remove surrounding quotes
    let content = if trimmed.starts_with('\'') && trimmed.ends_with('\'') {
        &trimmed[1..trimmed.len() - 1]
    } else if trimmed.starts_with('"') && trimmed.ends_with('"') {
        &trimmed[1..trimmed.len() - 1]
    } else {
        return Err(format!("Invalid quoted string: {}", quoted).into());
    };

    // Process escape sequences
    Ok(process_escapes(content))
}

/// Process escape sequences in a string.
pub fn process_escapes(s: &str) -> String {
    s.replace("\\\\", "\\")
        .replace("\\'", "'")
        .replace("\\\"", "\"")
        .replace("\\n", "\n")
        .replace("\\r", "\r")
        .replace("\\t", "\t")
}

/// Parse join type from string representation.
pub fn parse_join_type(s: &str) -> Result<JoinTypeOption, BundlebaseError> {
    let normalized = s.trim().to_lowercase();
    Ok(match normalized.as_str() {
        "inner" => JoinTypeOption::Inner,
        "left" => JoinTypeOption::Left,
        "right" => JoinTypeOption::Right,
        "full" | "outer" | "full outer" => JoinTypeOption::Full,
        _ => return Err(format!("Unknown join type: {}", s).into()),
    })
}

/// Escape a string value for use in a SQL statement.
///
/// Returns a single-quoted string with special characters escaped.
pub fn escape_string(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t");
    format!("'{}'", escaped)
}

/// Check if a SQL string appears to be a bundlebase command statement.
///
/// Returns true if the SQL starts with a bundlebase command keyword,
/// false if it appears to be standard SQL that should be passed to DataFusion.
///
/// This function does a quick keyword check without full parsing.
pub fn is_command_statement(sql: &str) -> bool {
    let first_keyword = first_keyword(sql);
    all_statement_keywords().contains(&first_keyword.as_str())
}

/// Extract the first keyword from a SQL string.
pub fn first_keyword(sql: &str) -> String {
    sql.trim()
        .split_whitespace()
        .next()
        .unwrap_or("")
        .to_uppercase()
}

/// Returns all statement keywords that indicate a bundlebase command.
///
/// Derived from the first word of each key in `available_commands()`.
pub fn all_statement_keywords() -> Vec<&'static str> {
    let mut seen = std::collections::HashSet::new();
    let mut keywords = Vec::new();
    for key in available_commands().keys() {
        let first_word = key.split_whitespace().next().unwrap_or(key);
        if seen.insert(first_word) {
            keywords.push(first_word);
        }
    }
    keywords
}

/// Returns a map of command names to their syntax descriptions.
///
/// This delegates to `BundleCommand::available_commands()` which is auto-generated
/// by the `register_commands!` macro, ensuring every registered command has a syntax entry.
pub fn available_commands() -> std::collections::HashMap<&'static str, &'static str> {
    super::BundleCommand::available_commands()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_command_statement() {
        assert!(is_command_statement("FILTER WHERE x = 1"));
        assert!(is_command_statement("ATTACH 'file.csv'"));
        assert!(is_command_statement("COMMIT 'message'"));
        // SELECT is standard SQL, not a bundlebase command
        assert!(!is_command_statement("SELECT * FROM bundle"));
        // Standard SQL that doesn't start with our keywords
        assert!(!is_command_statement("INSERT INTO table VALUES (1)"));
        assert!(!is_command_statement("UPDATE table SET x = 1"));
        assert!(!is_command_statement("DELETE FROM table"));
    }

    #[test]
    fn test_first_keyword() {
        assert_eq!(first_keyword("FILTER WHERE x = 1"), "FILTER");
        assert_eq!(first_keyword("  attach 'file.csv'"), "ATTACH");
        assert_eq!(first_keyword(""), "");
    }

    #[test]
    fn test_available_commands_has_entries() {
        let map = available_commands();
        assert!(map.len() > 20);
        assert!(map.contains_key("FILTER"));
        assert!(map.contains_key("ATTACH"));
    }
}
