//! Pest parser infrastructure for bundlebase custom SQL grammar.
//!
//! This module provides:
//! - The `BundlebaseParser` struct generated by pest
//! - Helper functions for parsing common elements (strings, identifiers, etc.)
//! - Error formatting utilities

use crate::bundle::pack::JoinTypeOption;
use crate::BundlebaseError;
use pest_derive::Parser;

/// Pest parser for bundlebase custom SQL grammar.
///
/// This parser handles bundlebase-specific syntax like FILTER, ATTACH, JOIN, etc.
/// Standard SQL is handled by sqlparser-rs.
#[derive(Parser)]
#[grammar = "bundle/command/parser/grammar.pest"]
pub struct BundlebaseParser;

/// Format a pest error into a user-friendly BundlebaseError.
pub fn format_pest_error(error: pest::error::Error<Rule>, sql: &str) -> BundlebaseError {
    let (line, col) = match &error.line_col {
        pest::error::LineColLocation::Pos((l, c)) => (*l, *c),
        pest::error::LineColLocation::Span((l, c), _) => (*l, *c),
    };

    format!(
        "Syntax error at line {}, column {}:\n{}\n\nSQL:\n{}",
        line, col, error, sql
    )
    .into()
}

/// Extract string content from a quoted string, handling escape sequences.
///
/// Supports both single-quoted ('...') and double-quoted ("...") strings.
pub fn extract_string_content(quoted: &str) -> Result<String, BundlebaseError> {
    let trimmed = quoted.trim();

    // Remove surrounding quotes
    let content = if trimmed.starts_with('\'') && trimmed.ends_with('\'') {
        &trimmed[1..trimmed.len() - 1]
    } else if trimmed.starts_with('"') && trimmed.ends_with('"') {
        &trimmed[1..trimmed.len() - 1]
    } else {
        return Err(format!("Invalid quoted string: {}", quoted).into());
    };

    // Process escape sequences
    Ok(process_escapes(content))
}

/// Process escape sequences in a string.
pub fn process_escapes(s: &str) -> String {
    s.replace("\\\\", "\\")
        .replace("\\'", "'")
        .replace("\\\"", "\"")
        .replace("\\n", "\n")
        .replace("\\r", "\r")
        .replace("\\t", "\t")
}

/// Parse join type from string representation.
pub fn parse_join_type(s: &str) -> Result<JoinTypeOption, BundlebaseError> {
    let normalized = s.trim().to_lowercase();
    Ok(match normalized.as_str() {
        "inner" => JoinTypeOption::Inner,
        "left" => JoinTypeOption::Left,
        "right" => JoinTypeOption::Right,
        "full" | "outer" | "full outer" => JoinTypeOption::Full,
        _ => return Err(format!("Unknown join type: {}", s).into()),
    })
}

/// Escape a string value for use in a SQL statement.
///
/// Returns a single-quoted string with special characters escaped.
pub fn escape_string(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t");
    format!("'{}'", escaped)
}
