//! Pest parser infrastructure for bundlebase custom SQL grammar.
//!
//! This module provides:
//! - The `BundlebaseParser` struct generated by pest
//! - Helper functions for parsing common elements (strings, identifiers, etc.)
//! - Error formatting utilities

use bundlebase::JoinTypeOption;
use bundlebase_common::BundlebaseError;
use pest_derive::Parser;

/// Pest parser for bundlebase custom SQL grammar.
///
/// This parser handles bundlebase-specific syntax like FILTER, ATTACH, JOIN, etc.
/// Standard SQL is handled by sqlparser-rs.
#[derive(Parser)]
#[grammar = "parser/grammar.pest"]
pub struct BundlebaseParser;

/// Format a pest error into a user-friendly BundlebaseError.
///
/// Adds command-aware hints in front of pest's raw output: when the parser was
/// expecting a `quoted_string` (or other recognizable token) and the input
/// starts with a known bundlebase command keyword, prepend a one-line "what
/// this command needs" message looked up from `available_commands()`. The
/// pest detail block stays at the bottom for diagnostics.
pub fn format_pest_error(error: pest::error::Error<Rule>, sql: &str) -> BundlebaseError {
    let (line, col) = match &error.line_col {
        pest::error::LineColLocation::Pos((l, c)) => (*l, *c),
        pest::error::LineColLocation::Span((l, c), _) => (*l, *c),
    };

    let hint = command_hint_for(&error, sql);
    let hint_line = match hint {
        Some(h) => format!("\n\nHint: {}", h),
        None => String::new(),
    };

    format!(
        "Syntax error at line {}, column {}:\n{}{}\n\nSQL:\n{}",
        line, col, error, hint_line, sql
    )
    .into()
}

/// Produce a command-specific hint when the pest error is "missing required
/// token after the command keyword". Returns `Some(hint)` only when we can
/// match the input to a known bundlebase command and the parser was expecting
/// at least one of the tokens we know how to describe.
fn command_hint_for(error: &pest::error::Error<Rule>, sql: &str) -> Option<String> {
    let positives = match &error.variant {
        pest::error::ErrorVariant::ParsingError { positives, .. } => positives,
        _ => return None,
    };
    if positives.is_empty() {
        return None;
    }

    // Translate the expected pest rule names into something a user understands.
    let expected_label = describe_expected(positives);

    // Look up the command's usage line — if we can identify the command from
    // its first keyword. Two-word commands (e.g. `FETCH ALL`) need a fallback
    // to the single-keyword form.
    let trimmed = sql.trim();
    let upper = trimmed.to_uppercase();
    let cmds = available_commands();
    let usage = cmds
        .iter()
        .filter(|(key, _)| upper.starts_with(*key))
        .max_by_key(|(key, _)| key.len())
        .map(|(_, usage)| *usage);

    match (expected_label, usage) {
        (Some(label), Some(usage)) => Some(format!(
            "expected {} after the command keyword. Usage: {}",
            label, usage
        )),
        (Some(label), None) => Some(format!("expected {}", label)),
        (None, Some(usage)) => Some(format!("usage: {}", usage)),
        (None, None) => None,
    }
}

/// Map a list of expected pest rules into a single human-readable string.
/// Returns `None` when none of the positives are ones we know how to phrase.
fn describe_expected(positives: &[Rule]) -> Option<String> {
    let mut labels: Vec<&'static str> = positives
        .iter()
        .filter_map(|rule| match rule {
            Rule::quoted_string => Some("a quoted string (e.g. 'message' or $$message$$)"),
            Rule::dotted_identifier => Some("a dotted name (e.g. acme.weather)"),
            Rule::identifier => Some("an identifier"),
            Rule::number => Some("a number"),
            Rule::source_args => Some("a WITH (key = 'value', ...) clause"),
            Rule::platform_map => Some("a platform map { 'os/arch' : '...', ... }"),
            _ => None,
        })
        .collect();
    labels.sort();
    labels.dedup();
    if labels.is_empty() {
        None
    } else if labels.len() == 1 {
        Some(labels[0].to_string())
    } else {
        let last = labels.pop().unwrap();
        Some(format!("{}, or {}", labels.join(", "), last))
    }
}

/// Extract identifier content, stripping surrounding double quotes if present.
///
/// Handles both bare identifiers (`my_column`) and quoted identifiers (`"My Column"`).
/// Quoted identifiers allow any characters including spaces, dots, and special characters.
pub fn extract_identifier(pair: &pest::iterators::Pair<Rule>) -> String {
    let s = pair.as_str();
    if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
        s[1..s.len() - 1].to_string()
    } else {
        s.to_string()
    }
}

/// Quote an identifier for use in SQL statements if it contains special characters.
///
/// Returns the identifier bare if it only contains `[a-zA-Z0-9_]` and starts with
/// a letter or underscore. Otherwise wraps it in double quotes.
pub fn quote_identifier(name: &str) -> String {
    let needs_quoting = name.is_empty()
        || !name
            .chars()
            .next()
            .map(|c| c.is_ascii_alphabetic() || c == '_')
            .unwrap_or(false)
        || !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    if needs_quoting {
        format!("\"{}\"", name)
    } else {
        name.to_string()
    }
}

/// Extract string content from a quoted string, handling escape sequences.
///
/// Supports single-quoted ('...'), double-quoted ("..."), and dollar-quoted ($$...$$) strings.
/// Dollar-quoted strings are returned as-is with no escape processing.
pub fn extract_string_content(quoted: &str) -> Result<String, BundlebaseError> {
    let trimmed = quoted.trim();

    if trimmed.starts_with("$$") && trimmed.ends_with("$$") && trimmed.len() >= 4 {
        // Dollar-quoted: raw content, no escape processing
        return Ok(trimmed[2..trimmed.len() - 2].to_string());
    }

    // Remove surrounding quotes
    let content = if trimmed.starts_with('\'') && trimmed.ends_with('\'') {
        &trimmed[1..trimmed.len() - 1]
    } else if trimmed.starts_with('"') && trimmed.ends_with('"') {
        &trimmed[1..trimmed.len() - 1]
    } else {
        return Err(format!("Invalid quoted string: {}", quoted).into());
    };

    // Process escape sequences
    Ok(process_escapes(content))
}

/// Process escape sequences in a string.
pub fn process_escapes(s: &str) -> String {
    s.replace("\\\\", "\\")
        .replace("\\'", "'")
        .replace("''", "'") // SQL-style escaped single quote
        .replace("\\\"", "\"")
        .replace("\\n", "\n")
        .replace("\\r", "\r")
        .replace("\\t", "\t")
}

/// Parse join type from string representation.
pub fn parse_join_type(s: &str) -> Result<JoinTypeOption, BundlebaseError> {
    let normalized = s.trim().to_lowercase();
    Ok(match normalized.as_str() {
        "inner" => JoinTypeOption::Inner,
        "left" => JoinTypeOption::Left,
        "right" => JoinTypeOption::Right,
        "full" | "outer" | "full outer" => JoinTypeOption::Full,
        _ => return Err(format!("Unknown join type: {}", s).into()),
    })
}

/// Escape a string value for use in a SQL statement.
///
/// Uses dollar-quoting ($$...$$) when the string contains single quotes or literal newlines,
/// since dollar-quoted strings need no escaping and preserve content exactly.
/// Falls back to single-quoted with SQL escaping otherwise, or when the string contains `$$`.
pub fn escape_string(s: &str) -> String {
    // Use dollar-quoting when it's beneficial and safe (content doesn't contain $$)
    if !s.contains("$$") && (s.contains('\'') || s.contains('\n') || s.contains('\r')) {
        return format!("$${}$$", s);
    }

    let escaped = s
        .replace('\'', "''") // SQL-style: ' → ''
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t");
    format!("'{}'", escaped)
}

/// Check if a SQL string appears to be a bundlebase command statement.
///
/// Returns true if the SQL starts with a bundlebase command keyword,
/// false if it appears to be standard SQL that should be passed to DataFusion.
///
/// This function does a quick keyword check without full parsing.
pub fn is_command_statement(sql: &str) -> bool {
    let first_keyword = first_keyword(sql);
    all_statement_keywords().contains(&first_keyword.as_str())
}

/// Extract the first keyword from a SQL string.
pub fn first_keyword(sql: &str) -> String {
    sql.trim()
        .split_whitespace()
        .next()
        .unwrap_or("")
        .to_uppercase()
}

/// Returns all statement keywords that indicate a bundlebase command.
///
/// Derived from the first word of each key in `available_commands()`.
pub fn all_statement_keywords() -> Vec<&'static str> {
    let mut seen = std::collections::HashSet::new();
    let mut keywords = Vec::new();
    for key in available_commands().keys() {
        let first_word = key.split_whitespace().next().unwrap_or(key);
        if seen.insert(first_word) {
            keywords.push(first_word);
        }
    }
    keywords
}

/// Split input into individual statement strings, respecting quoted strings.
///
/// Uses the `multi_statement` grammar rule to properly handle semicolons
/// inside single-quoted strings. Returns the trimmed text of each statement.
/// Empty statements (from trailing `;`) are skipped.
pub fn split_statements(input: &str) -> Result<Vec<&str>, BundlebaseError> {
    use pest::Parser;

    let pairs = BundlebaseParser::parse(Rule::multi_statement, input)
        .map_err(|e| format_pest_error(e, input))?;

    let mut statements = Vec::new();
    for pair in pairs {
        for inner in pair.into_inner() {
            if inner.as_rule() == Rule::statement_text {
                let text = inner.as_str().trim();
                if !text.is_empty() {
                    statements.push(text);
                }
            }
        }
    }

    Ok(statements)
}

/// Returns true when `input` parses as one or more `;`-terminated statements
/// with no trailing partial statement, no unterminated string, and no
/// unterminated dollar-quoted block.
///
/// Used by the REPL to decide whether [Enter] should submit the buffer or
/// drop down to a continuation line. Callers that already pass complete
/// statements (Python, Flight, MCP) don't need this — they can keep using
/// `split_statements` / `parse` directly.
pub fn is_input_complete(input: &str) -> bool {
    use pest::Parser;
    BundlebaseParser::parse(Rule::repl_complete, input).is_ok()
}

/// Returns a map of command names to their syntax descriptions.
///
/// This delegates to `BundleCommand::available_commands()` which is auto-generated
/// by the `register_commands!` macro, ensuring every registered command has a syntax entry.
pub fn available_commands() -> std::collections::HashMap<&'static str, &'static str> {
    crate::BundleCommand::available_commands()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_command_statement() {
        assert!(is_command_statement("FILTER WHERE x = 1"));
        assert!(is_command_statement("ATTACH 'file.csv'"));
        assert!(is_command_statement("COMMIT 'message'"));
        // SELECT is standard SQL, not a bundlebase command
        assert!(!is_command_statement("SELECT * FROM bundle"));
        // Standard SQL that doesn't start with our keywords
        assert!(!is_command_statement("INSERT INTO table VALUES (1)"));
        assert!(is_command_statement("UPDATE bundle SET x = 1 WHERE y = 2"));
        assert!(is_command_statement("DELETE FROM bundle WHERE x = 1"));
    }

    #[test]
    fn test_first_keyword() {
        assert_eq!(first_keyword("FILTER WHERE x = 1"), "FILTER");
        assert_eq!(first_keyword("  attach 'file.csv'"), "ATTACH");
        assert_eq!(first_keyword(""), "");
    }

    #[test]
    fn test_available_commands_has_entries() {
        let map = available_commands();
        assert!(map.len() > 20);
        assert!(map.contains_key("FILTER"));
        assert!(map.contains_key("ATTACH"));
    }

    #[test]
    fn test_is_input_complete() {
        // Single statement with trailing semi → complete
        assert!(is_input_complete("SELECT 1;"));
        assert!(is_input_complete("SELECT 1;\n"));
        assert!(is_input_complete("  SELECT 1 ;  "));

        // Multi-line statement, terminated → complete
        assert!(is_input_complete(
            "SELECT *\nFROM bundle\nWHERE x = 1\nGROUP BY y;"
        ));

        // Multiple statements → complete
        assert!(is_input_complete("SELECT 1; SELECT 2;"));

        // Missing trailing semi → incomplete (REPL keeps prompting)
        assert!(!is_input_complete("SELECT 1"));
        assert!(!is_input_complete("SELECT *\nFROM bundle"));
        assert!(!is_input_complete("SELECT 1;\nSELECT 2"));

        // Semicolon inside a single-quoted string is NOT a terminator
        assert!(!is_input_complete("SELECT 'a;b'"));
        assert!(is_input_complete("SELECT 'a;b';"));

        // Unterminated string → incomplete
        assert!(!is_input_complete("SELECT 'unterminated"));

        // Dollar-quoted block with `;` inside is one statement
        assert!(is_input_complete("COMMIT $$ hello; world $$;"));
        assert!(!is_input_complete("COMMIT $$ hello; world $$"));

        // Unterminated `$$` opener → incomplete (the wildcard branch refuses
        // to swallow `$$`, forcing it through `quoted_string` which needs a
        // balanced closer).
        assert!(!is_input_complete("COMMIT $$ hello;"));
        assert!(!is_input_complete("COMMIT $$ hello\nworld"));

        // Empty input → not complete (validator short-circuits this case)
        assert!(!is_input_complete(""));
    }

    #[test]
    fn test_split_single_statement() {
        let stmts = split_statements("SELECT * FROM bundle").unwrap();
        assert_eq!(stmts, vec!["SELECT * FROM bundle"]);
    }

    #[test]
    fn test_split_two_statements() {
        let stmts = split_statements("ATTACH 'data.csv'; SHOW HISTORY").unwrap();
        assert_eq!(stmts, vec!["ATTACH 'data.csv'", "SHOW HISTORY"]);
    }

    #[test]
    fn test_split_trailing_semicolon() {
        let stmts = split_statements("SHOW HISTORY;").unwrap();
        assert_eq!(stmts, vec!["SHOW HISTORY"]);
    }

    #[test]
    fn test_split_semicolon_in_quotes() {
        let stmts = split_statements("COMMIT 'msg with ; in it'; SHOW STATUS").unwrap();
        assert_eq!(stmts, vec!["COMMIT 'msg with ; in it'", "SHOW STATUS"]);
    }

    #[test]
    fn test_split_escaped_quotes() {
        let stmts = split_statements("COMMIT 'it''s done'; SHOW HISTORY").unwrap();
        assert_eq!(stmts, vec!["COMMIT 'it''s done'", "SHOW HISTORY"]);
    }

    #[test]
    fn test_split_whitespace_handling() {
        let stmts = split_statements("  SHOW HISTORY ;  SHOW STATUS  ").unwrap();
        assert_eq!(stmts, vec!["SHOW HISTORY", "SHOW STATUS"]);
    }

    #[test]
    fn test_split_multiple_statements() {
        let stmts = split_statements("ATTACH 'a.csv'; FILTER WHERE x > 1; COMMIT 'done'").unwrap();
        assert_eq!(
            stmts,
            vec!["ATTACH 'a.csv'", "FILTER WHERE x > 1", "COMMIT 'done'"]
        );
    }

    // --- Dollar-quoting tests ---

    #[test]
    fn test_extract_dollar_quoted_simple() {
        assert_eq!(extract_string_content("$$hello$$").unwrap(), "hello");
    }

    #[test]
    fn test_extract_dollar_quoted_with_single_quotes() {
        assert_eq!(
            extract_string_content("$$it's a test$$").unwrap(),
            "it's a test"
        );
    }

    #[test]
    fn test_extract_dollar_quoted_with_newlines() {
        assert_eq!(
            extract_string_content("$$line1\nline2$$").unwrap(),
            "line1\nline2"
        );
    }

    #[test]
    fn test_extract_dollar_quoted_json() {
        let json = r#"{"key": "value", "nested": {"a": 1}}"#;
        let input = format!("$${}$$", json);
        assert_eq!(extract_string_content(&input).unwrap(), json);
    }

    #[test]
    fn test_extract_dollar_quoted_empty() {
        assert_eq!(extract_string_content("$$$$").unwrap(), "");
    }

    #[test]
    fn test_extract_dollar_quoted_no_escape_processing() {
        // Dollar-quoted strings are raw — backslash sequences are NOT processed
        assert_eq!(
            extract_string_content(r"$$hello\nworld$$").unwrap(),
            r"hello\nworld"
        );
    }

    #[test]
    fn test_escape_string_uses_dollar_quoting_for_single_quotes() {
        let result = escape_string("it's here");
        assert_eq!(result, "$$it's here$$");
    }

    #[test]
    fn test_escape_string_uses_dollar_quoting_for_newlines() {
        let result = escape_string("line1\nline2");
        assert_eq!(result, "$$line1\nline2$$");
    }

    #[test]
    fn test_escape_string_plain_uses_single_quotes() {
        let result = escape_string("simple");
        assert_eq!(result, "'simple'");
    }

    #[test]
    fn test_escape_string_with_dollar_dollar_falls_back_to_single_quotes() {
        // String contains $$ so we can't dollar-quote it
        let result = escape_string("contains $$dollar$$ and 'quotes'");
        assert_eq!(result, "'contains $$dollar$$ and ''quotes'''");
    }

    #[test]
    fn test_split_semicolon_in_dollar_quoted() {
        let stmts = split_statements("COMMIT $$msg; with semicolon$$; SHOW STATUS").unwrap();
        assert_eq!(stmts, vec!["COMMIT $$msg; with semicolon$$", "SHOW STATUS"]);
    }

    #[test]
    fn test_split_newline_in_dollar_quoted() {
        let input = "COMMIT $$line1\nline2$$; SHOW STATUS";
        let stmts = split_statements(input).unwrap();
        assert_eq!(stmts, vec!["COMMIT $$line1\nline2$$", "SHOW STATUS"]);
    }
}
