//! Pest parser infrastructure for bundlebase custom SQL grammar.
//!
//! This module provides:
//! - The `BundlebaseParser` struct generated by pest
//! - Helper functions for parsing common elements (strings, identifiers, etc.)
//! - Error formatting utilities

use bundlebase::JoinTypeOption;
use bundlebase_common::BundlebaseError;
use pest_derive::Parser;

/// Pest parser for bundlebase custom SQL grammar.
///
/// This parser handles bundlebase-specific syntax like FILTER, ATTACH, JOIN, etc.
/// Standard SQL is handled by sqlparser-rs.
#[derive(Parser)]
#[grammar = "parser/grammar.pest"]
pub struct BundlebaseParser;

/// Format a pest error into a user-friendly BundlebaseError.
pub fn format_pest_error(error: pest::error::Error<Rule>, sql: &str) -> BundlebaseError {
    let (line, col) = match &error.line_col {
        pest::error::LineColLocation::Pos((l, c)) => (*l, *c),
        pest::error::LineColLocation::Span((l, c), _) => (*l, *c),
    };

    format!(
        "Syntax error at line {}, column {}:\n{}\n\nSQL:\n{}",
        line, col, error, sql
    )
    .into()
}

/// Extract string content from a quoted string, handling escape sequences.
///
/// Supports both single-quoted ('...') and double-quoted ("...") strings.
pub fn extract_string_content(quoted: &str) -> Result<String, BundlebaseError> {
    let trimmed = quoted.trim();

    // Remove surrounding quotes
    let content = if trimmed.starts_with('\'') && trimmed.ends_with('\'') {
        &trimmed[1..trimmed.len() - 1]
    } else if trimmed.starts_with('"') && trimmed.ends_with('"') {
        &trimmed[1..trimmed.len() - 1]
    } else {
        return Err(format!("Invalid quoted string: {}", quoted).into());
    };

    // Process escape sequences
    Ok(process_escapes(content))
}

/// Process escape sequences in a string.
pub fn process_escapes(s: &str) -> String {
    s.replace("\\\\", "\\")
        .replace("\\'", "'")
        .replace("''", "'")  // SQL-style escaped single quote
        .replace("\\\"", "\"")
        .replace("\\n", "\n")
        .replace("\\r", "\r")
        .replace("\\t", "\t")
}

/// Parse join type from string representation.
pub fn parse_join_type(s: &str) -> Result<JoinTypeOption, BundlebaseError> {
    let normalized = s.trim().to_lowercase();
    Ok(match normalized.as_str() {
        "inner" => JoinTypeOption::Inner,
        "left" => JoinTypeOption::Left,
        "right" => JoinTypeOption::Right,
        "full" | "outer" | "full outer" => JoinTypeOption::Full,
        _ => return Err(format!("Unknown join type: {}", s).into()),
    })
}

/// Escape a string value for use in a SQL statement.
///
/// Returns a single-quoted string with special characters escaped.
pub fn escape_string(s: &str) -> String {
    let escaped = s
        .replace('\'', "''")   // SQL-style: ' → ''
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t");
    format!("'{}'", escaped)
}

/// Check if a SQL string appears to be a bundlebase command statement.
///
/// Returns true if the SQL starts with a bundlebase command keyword,
/// false if it appears to be standard SQL that should be passed to DataFusion.
///
/// This function does a quick keyword check without full parsing.
pub fn is_command_statement(sql: &str) -> bool {
    let first_keyword = first_keyword(sql);
    all_statement_keywords().contains(&first_keyword.as_str())
}

/// Extract the first keyword from a SQL string.
pub fn first_keyword(sql: &str) -> String {
    sql.trim()
        .split_whitespace()
        .next()
        .unwrap_or("")
        .to_uppercase()
}

/// Returns all statement keywords that indicate a bundlebase command.
///
/// Derived from the first word of each key in `available_commands()`.
pub fn all_statement_keywords() -> Vec<&'static str> {
    let mut seen = std::collections::HashSet::new();
    let mut keywords = Vec::new();
    for key in available_commands().keys() {
        let first_word = key.split_whitespace().next().unwrap_or(key);
        if seen.insert(first_word) {
            keywords.push(first_word);
        }
    }
    keywords
}

/// Split input into individual statement strings, respecting quoted strings.
///
/// Uses the `multi_statement` grammar rule to properly handle semicolons
/// inside single-quoted strings. Returns the trimmed text of each statement.
/// Empty statements (from trailing `;`) are skipped.
pub fn split_statements(input: &str) -> Result<Vec<&str>, BundlebaseError> {
    use pest::Parser;

    let pairs = BundlebaseParser::parse(Rule::multi_statement, input)
        .map_err(|e| format_pest_error(e, input))?;

    let mut statements = Vec::new();
    for pair in pairs {
        for inner in pair.into_inner() {
            if inner.as_rule() == Rule::statement_text {
                let text = inner.as_str().trim();
                if !text.is_empty() {
                    statements.push(text);
                }
            }
        }
    }

    Ok(statements)
}

/// Returns a map of command names to their syntax descriptions.
///
/// This delegates to `BundleCommand::available_commands()` which is auto-generated
/// by the `register_commands!` macro, ensuring every registered command has a syntax entry.
pub fn available_commands() -> std::collections::HashMap<&'static str, &'static str> {
    crate::BundleCommand::available_commands()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_command_statement() {
        assert!(is_command_statement("FILTER WHERE x = 1"));
        assert!(is_command_statement("ATTACH 'file.csv'"));
        assert!(is_command_statement("COMMIT 'message'"));
        // SELECT is standard SQL, not a bundlebase command
        assert!(!is_command_statement("SELECT * FROM bundle"));
        // Standard SQL that doesn't start with our keywords
        assert!(!is_command_statement("INSERT INTO table VALUES (1)"));
        assert!(!is_command_statement("UPDATE table SET x = 1"));
        assert!(!is_command_statement("DELETE FROM table"));
    }

    #[test]
    fn test_first_keyword() {
        assert_eq!(first_keyword("FILTER WHERE x = 1"), "FILTER");
        assert_eq!(first_keyword("  attach 'file.csv'"), "ATTACH");
        assert_eq!(first_keyword(""), "");
    }

    #[test]
    fn test_available_commands_has_entries() {
        let map = available_commands();
        assert!(map.len() > 20);
        assert!(map.contains_key("FILTER"));
        assert!(map.contains_key("ATTACH"));
    }

    #[test]
    fn test_split_single_statement() {
        let stmts = split_statements("SELECT * FROM bundle").unwrap();
        assert_eq!(stmts, vec!["SELECT * FROM bundle"]);
    }

    #[test]
    fn test_split_two_statements() {
        let stmts = split_statements("ATTACH 'data.csv'; SHOW HISTORY").unwrap();
        assert_eq!(stmts, vec!["ATTACH 'data.csv'", "SHOW HISTORY"]);
    }

    #[test]
    fn test_split_trailing_semicolon() {
        let stmts = split_statements("SHOW HISTORY;").unwrap();
        assert_eq!(stmts, vec!["SHOW HISTORY"]);
    }

    #[test]
    fn test_split_semicolon_in_quotes() {
        let stmts = split_statements("COMMIT 'msg with ; in it'; SHOW STATUS").unwrap();
        assert_eq!(stmts, vec!["COMMIT 'msg with ; in it'", "SHOW STATUS"]);
    }

    #[test]
    fn test_split_escaped_quotes() {
        let stmts = split_statements("COMMIT 'it''s done'; SHOW HISTORY").unwrap();
        assert_eq!(stmts, vec!["COMMIT 'it''s done'", "SHOW HISTORY"]);
    }

    #[test]
    fn test_split_whitespace_handling() {
        let stmts = split_statements("  SHOW HISTORY ;  SHOW STATUS  ").unwrap();
        assert_eq!(stmts, vec!["SHOW HISTORY", "SHOW STATUS"]);
    }

    #[test]
    fn test_split_multiple_statements() {
        let stmts = split_statements("ATTACH 'a.csv'; FILTER WHERE x > 1; COMMIT 'done'").unwrap();
        assert_eq!(stmts, vec!["ATTACH 'a.csv'", "FILTER WHERE x > 1", "COMMIT 'done'"]);
    }
}
